/**
 * Real screens from the deployed Nivex prototype, by logical name.
 *
 * Generated by `scripts/process-nivex-shots.mjs` — do not hand-edit. The hash
 * in each filename is the file's own content, so re-capturing a screen changes
 * its URL and no cache can serve the previous version. See the script header.
 */
export const nivexShots = {
  "admin-cases": "/images/v3/nivex/admin-cases.77e41f8d.webp",
  "admin-investors": "/images/v3/nivex/admin-investors.7cb2fad4.webp",
  "admin-overview": "/images/v3/nivex/admin-overview.fed3082d.webp",
  "advisor-clients": "/images/v3/nivex/advisor-clients.65f3e885.webp",
  "audit-prescription": "/images/v3/nivex/audit-prescription.c2f4e000.webp",
  "choose-service": "/images/v3/nivex/choose-service.87ae890e.webp",
  "dashboard": "/images/v3/nivex/dashboard.a04663a7.webp",
  "goals": "/images/v3/nivex/goals.ec916db1.webp",
  "import-portfolio": "/images/v3/nivex/import-portfolio.c7e29a07.webp",
  "portfolio": "/images/v3/nivex/portfolio.3c275ede.webp",
  "splash": "/images/v3/nivex/splash.062fcfd5.webp",
  "team-login": "/images/v3/nivex/team-login.4d4002ce.webp",
  "trades": "/images/v3/nivex/trades.47cd307d.webp",
} as const;

export type NivexShot = keyof typeof nivexShots;
