/**
 * Sparrow product screens, by logical name.
 *
 * Generated by `scripts/process-sparrow-shots.mjs` — do not hand-edit.
 *
 * `w`/`h` are the real pixel dimensions. The case study frames each shot at
 * its own ratio from these, because Sparrow's app screenshots are about 1.91
 * wide and cropping them into a 16:10 frame would cut the panels off both
 * sides — and the panel layout is the thing the case study is about.
 *
 * The hash in each filename is the file's own content, so replacing a screen
 * changes its URL and no cache can serve the previous one.
 */
export type SparrowShot = {
  src: string;
  w: number;
  h: number;
};

export const sparrowShots = {
  "api-testing": { src: "/images/v3/sparrow/api-testing.6d0c3000.webp", w: 1919, h: 1003 },
  "request-body": { src: "/images/v3/sparrow/request-body.c20adf3c.webp", w: 1919, h: 1004 },
  "assertions": { src: "/images/v3/sparrow/assertions.9c04ad16.webp", w: 1919, h: 1005 },
  "hub": { src: "/images/v3/sparrow/hub.57309948.webp", w: 1919, h: 1003 },
  "hub-members": { src: "/images/v3/sparrow/hub-members.13c9c04e.webp", w: 1919, h: 1003 },
  "hub-settings": { src: "/images/v3/sparrow/hub-settings.73042656.webp", w: 1918, h: 1007 },
  "workspace": { src: "/images/v3/sparrow/workspace.02aede59.webp", w: 1919, h: 1005 },
  "workspace-manage": { src: "/images/v3/sparrow/workspace-manage.7c4ee947.webp", w: 1919, h: 1005 },
  "collections": { src: "/images/v3/sparrow/collections.90d1c9b8.webp", w: 1907, h: 1009 },
  "test-flows": { src: "/images/v3/sparrow/test-flows.b1705447.webp", w: 1907, h: 999 },
  "marketplace": { src: "/images/v3/sparrow/marketplace.c2184ed6.webp", w: 1309, h: 750 },
  "share-workspace": { src: "/images/v3/sparrow/share-workspace.06425165.webp", w: 1919, h: 1006 },
  "first-workspace": { src: "/images/v3/sparrow/first-workspace.e681640b.webp", w: 1919, h: 1005 },
  "mock-server": { src: "/images/v3/sparrow/mock-server.d01967e3.webp", w: 1919, h: 1000 },
  "overview": { src: "/images/v3/sparrow/overview.938a08a1.webp", w: 1287, h: 648 },
} as const satisfies Record<string, SparrowShot>;

export type SparrowShotName = keyof typeof sparrowShots;
